# Generated by Django 4.2.6 on 2023-10-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('symbol', models.CharField(max_length=100, verbose_name='symbol')),
            ],
            options={
                'verbose_name': 'token',
                'verbose_name_plural': 'tokens',
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('pool_id', models.CharField(max_length=255, verbose_name='pool id (address)')),
                ('token_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pairs_token_1', to='data.token')),
                ('token_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pairs_token_2', to='data.token')),
            ],
            options={
                'verbose_name': 'pair',
                'verbose_name_plural': 'pairs',
            },
        ),
        migrations.CreateModel(
            name='HourlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('snapshot_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='pool id (address)')),
                ('timestamp', models.PositiveBigIntegerField(db_index=True, verbose_name='timestamp')),
                ('volume', models.PositiveBigIntegerField(help_text='volume in token units', verbose_name='volume')),
                ('volume_usd', models.PositiveBigIntegerField(verbose_name='volume (USD)')),
                ('token_1_balance', models.PositiveBigIntegerField(verbose_name='token 1 balance')),
                ('token_2_balance', models.PositiveBigIntegerField(verbose_name='token 2 balance')),
                ('token_1_price', models.FloatField(verbose_name='token 1 price (in token 2 units)')),
                ('token_1_price_usd', models.FloatField(verbose_name='price')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.pair')),
            ],
            options={
                'verbose_name': 'hourly snapshot',
                'verbose_name_plural': 'hourly snapshots',
                'ordering': ('timestamp',),
            },
        ),
    ]
