# Generated by Django 4.2.6 on 2023-10-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0005_run_from_timestamp_run_to_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='message',
            field=models.TextField(blank=True, verbose_name='message'),
        ),
    ]
